# fly.toml app configuration file generated for bingo on 2024-01-20T17:02:08+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bingo"
primary_region = "nrt"

[build]

[env]
  HOSTNAME = "0.0.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
